# Generated by Django 5.0.3 on 2024-04-12 10:55

import app_goods.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Good Type',
                'verbose_name_plural': 'Good Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('good_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_goods.goodtype')),
            ],
            options={
                'verbose_name': 'Good',
                'verbose_name_plural': 'Goods',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GoodTypeCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Good Type Cluster',
                'verbose_name_plural': 'Good Types Clusters',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['id', 'name'], name='app_goods_g_id_0a4279_idx'), models.Index(fields=['id'], name='app_goods_g_id_fb189d_idx'), models.Index(fields=['name'], name='app_goods_g_name_81be0e_idx')],
            },
        ),
        migrations.AddField(
            model_name='goodtype',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_goods.goodtypecluster'),
        ),
        migrations.CreateModel(
            name='GoodVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=11, unique=True, validators=[app_goods.models.validate_non_none])),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('stock_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('on_discount', models.BooleanField(default=False)),
                ('discount_percentage', models.IntegerField(default=0)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_goods.good')),
            ],
            options={
                'verbose_name': 'Good Variant',
                'verbose_name_plural': 'Good Variants',
                'ordering': ['update_date', 'amount', 'good', 'size', 'taste', 'sell_price', 'on_discount'],
            },
        ),
        migrations.CreateModel(
            name='GoodVarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='good_variants')),
                ('good_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='app_goods.goodvariant')),
            ],
            options={
                'verbose_name': 'Good Variant Photo',
                'verbose_name_plural': 'Good Variant Photos',
                'ordering': ['good_variant'],
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='producers')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Producer',
                'verbose_name_plural': 'Producers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['id', 'name'], name='app_goods_p_id_29af3b_idx'), models.Index(fields=['id'], name='app_goods_p_id_09b5f1_idx'), models.Index(fields=['name'], name='app_goods_p_name_ca44a0_idx')],
            },
        ),
        migrations.AddField(
            model_name='good',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_goods.producer'),
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['id', 'name'], name='app_goods_s_id_524dae_idx'), models.Index(fields=['id'], name='app_goods_s_id_d78cbb_idx'), models.Index(fields=['name'], name='app_goods_s_name_291420_idx')],
            },
        ),
        migrations.AddField(
            model_name='goodvariant',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_goods.size'),
        ),
        migrations.CreateModel(
            name='Taste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Taste',
                'verbose_name_plural': 'Tastes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['id', 'name'], name='app_goods_t_id_2847fb_idx'), models.Index(fields=['id'], name='app_goods_t_id_00fc6c_idx'), models.Index(fields=['name'], name='app_goods_t_name_e12e16_idx')],
            },
        ),
        migrations.AddField(
            model_name='goodvariant',
            name='taste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_goods.taste'),
        ),
        migrations.AddIndex(
            model_name='goodtype',
            index=models.Index(fields=['id', 'name'], name='app_goods_g_id_85b428_idx'),
        ),
        migrations.AddIndex(
            model_name='goodtype',
            index=models.Index(fields=['id'], name='app_goods_g_id_6faca3_idx'),
        ),
        migrations.AddIndex(
            model_name='goodtype',
            index=models.Index(fields=['name'], name='app_goods_g_name_bfc448_idx'),
        ),
        migrations.AddIndex(
            model_name='goodvarphoto',
            index=models.Index(fields=['id', 'good_variant'], name='app_goods_g_id_8ef4d4_idx'),
        ),
        migrations.AddIndex(
            model_name='goodvarphoto',
            index=models.Index(fields=['id'], name='app_goods_g_id_401e0f_idx'),
        ),
        migrations.AddIndex(
            model_name='goodvarphoto',
            index=models.Index(fields=['good_variant'], name='app_goods_g_good_va_bb2ef5_idx'),
        ),
        migrations.AddIndex(
            model_name='good',
            index=models.Index(fields=['id', 'name', 'good_type', 'producer'], name='app_goods_g_id_b5f3b1_idx'),
        ),
        migrations.AddIndex(
            model_name='good',
            index=models.Index(fields=['id'], name='app_goods_g_id_4f503d_idx'),
        ),
        migrations.AddIndex(
            model_name='good',
            index=models.Index(fields=['name'], name='app_goods_g_name_41638a_idx'),
        ),
        migrations.AddIndex(
            model_name='good',
            index=models.Index(fields=['good_type'], name='app_goods_g_good_ty_9afd30_idx'),
        ),
        migrations.AddIndex(
            model_name='good',
            index=models.Index(fields=['producer'], name='app_goods_g_produce_0508ff_idx'),
        ),
        migrations.AddIndex(
            model_name='goodvariant',
            index=models.Index(fields=['code', 'good', 'size', 'taste', 'sell_price', 'on_discount'], name='app_goods_g_code_96bcde_idx'),
        ),
        migrations.AddIndex(
            model_name='goodvariant',
            index=models.Index(fields=['code'], name='app_goods_g_code_5b80ad_idx'),
        ),
        migrations.AddIndex(
            model_name='goodvariant',
            index=models.Index(fields=['good'], name='app_goods_g_good_id_1193b5_idx'),
        ),
        migrations.AddIndex(
            model_name='goodvariant',
            index=models.Index(fields=['size'], name='app_goods_g_size_id_af8868_idx'),
        ),
        migrations.AddIndex(
            model_name='goodvariant',
            index=models.Index(fields=['taste'], name='app_goods_g_taste_i_17f34b_idx'),
        ),
        migrations.AddIndex(
            model_name='goodvariant',
            index=models.Index(fields=['sell_price'], name='app_goods_g_sell_pr_f613a8_idx'),
        ),
        migrations.AddIndex(
            model_name='goodvariant',
            index=models.Index(fields=['on_discount'], name='app_goods_g_on_disc_dca26c_idx'),
        ),
    ]
