# Generated by Django 5.0.3 on 2024-04-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='name_lower',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goodtype',
            name='name_lower',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goodtypecluster',
            name='name_lower',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goodvariant',
            name='name_lower',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
