# Generated by Django 5.0.3 on 2024-04-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0002_good_name_lower_goodtype_name_lower_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='goodtypecluster',
            name='app_goods_g_id_0a4279_idx',
        ),
        migrations.AddIndex(
            model_name='goodtypecluster',
            index=models.Index(fields=['id', 'name', 'name_lower'], name='app_goods_g_id_d5bfc0_idx'),
        ),
        migrations.AddIndex(
            model_name='goodtypecluster',
            index=models.Index(fields=['name_lower'], name='app_goods_g_name_lo_75e368_idx'),
        ),
    ]
