# Generated by Django 5.0.3 on 2024-04-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0003_remove_goodtypecluster_app_goods_g_id_0a4279_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='good',
            name='app_goods_g_id_b5f3b1_idx',
        ),
        migrations.RemoveIndex(
            model_name='goodtype',
            name='app_goods_g_id_85b428_idx',
        ),
        migrations.RemoveIndex(
            model_name='goodvariant',
            name='app_goods_g_code_96bcde_idx',
        ),
        migrations.AddIndex(
            model_name='good',
            index=models.Index(fields=['id', 'name', 'good_type', 'producer', 'name_lower'], name='app_goods_g_id_506a5c_idx'),
        ),
        migrations.AddIndex(
            model_name='good',
            index=models.Index(fields=['name_lower'], name='app_goods_g_name_lo_31b812_idx'),
        ),
        migrations.AddIndex(
            model_name='goodtype',
            index=models.Index(fields=['id', 'name', 'name_lower'], name='app_goods_g_id_eeab28_idx'),
        ),
        migrations.AddIndex(
            model_name='goodtype',
            index=models.Index(fields=['name_lower'], name='app_goods_g_name_lo_d9f912_idx'),
        ),
        migrations.AddIndex(
            model_name='goodvariant',
            index=models.Index(fields=['code', 'good', 'size', 'taste', 'sell_price', 'on_discount', 'name_lower'], name='app_goods_g_code_62c64f_idx'),
        ),
        migrations.AddIndex(
            model_name='goodvariant',
            index=models.Index(fields=['name_lower'], name='app_goods_g_name_lo_b652dc_idx'),
        ),
    ]
