# Generated by Django 5.0.3 on 2024-04-12 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0005_remove_producer_app_goods_p_id_29af3b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodtype',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_types', to='app_goods.goodtypecluster'),
        ),
    ]
