# Generated by Django 5.0.3 on 2024-05-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0006_alter_goodtype_cluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodvariant',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
