# Generated by Django 5.0.3 on 2024-06-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0010_alter_good_aim_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='sliders')),
            ],
            options={
                'verbose_name': 'Slider Image',
                'verbose_name_plural': 'Slider Images',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['id', 'title'], name='app_goods_s_id_4abc1f_idx'), models.Index(fields=['id'], name='app_goods_s_id_597069_idx'), models.Index(fields=['title'], name='app_goods_s_title_dac5b7_idx')],
            },
        ),
    ]
