# Generated by Django 5.0.3 on 2024-06-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0012_goodvariant_is_locked_goodvariant_stars_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodvariant',
            name='stars_amount',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
