# Generated by Django 5.0.3 on 2024-04-26 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_goods', '0006_alter_goodtype_cluster'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('total_discount', models.FloatField(blank=True, null=True)),
                ('total_clear_price', models.FloatField(blank=True, null=True)),
                ('invoice_status', models.CharField(choices=[('CREATED', 'Created'), ('PAYED', 'PAYED'), ('EXPIRED', 'Expired'), ('CANCELED', 'Canceled')], default='CREATED', max_length=10)),
                ('payment_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('order_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('good_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_goods.goodvariant')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_orders.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['session'], name='app_orders__session_087c5b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['create_date'], name='app_orders__create__28b3f0_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['update_date'], name='app_orders__update__c082df_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['total_price'], name='app_orders__total_p_e2c3ee_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['total_discount'], name='app_orders__total_d_c11468_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['total_clear_price'], name='app_orders__total_c_976657_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['invoice_status'], name='app_orders__invoice_00636c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_delivered'], name='app_orders__is_deli_d368b7_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='app_orders__order_i_29d974_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['good_variant'], name='app_orders__good_va_9999d5_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['amount'], name='app_orders__amount_1b16b4_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['create_date'], name='app_orders__create__1ed704_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['update_date'], name='app_orders__update__275c1c_idx'),
        ),
    ]
