# Generated by Django 5.0.3 on 2024-04-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0003_alter_order_total_clear_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice_status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('FILLED', 'Filled'), ('PAYED', 'PAYED'), ('EXPIRED', 'Expired'), ('CANCELED', 'Canceled')], default='CREATED', max_length=10),
        ),
    ]
