# Generated by Django 5.0.3 on 2024-04-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0004_alter_order_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('NP', 'Nove Poshta'), ('UP', 'Ukr Poshta'), ('SL', 'Sport Life')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='nova_post_address',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='np_city',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('OP', 'Online Payment'), ('CP', 'Cash Payment')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ukr_post_adress',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user_fio',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
