# Generated by Django 5.0.3 on 2024-04-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0005_order_delivery_type_order_nova_post_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('NP', 'Nova Poshta'), ('UP', 'Ukr Poshta'), ('SL', 'Sport Life')], max_length=2, null=True),
        ),
    ]
