# Generated by Django 5.0.3 on 2024-04-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0007_remove_order_np_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='np_city',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
