# Generated by Django 5.0.3 on 2024-05-07 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0011_alter_order_invoice_status'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='OrderFix',
        ),
        migrations.AlterModelOptions(
            name='orderfix',
            options={'verbose_name': 'OrderFix', 'verbose_name_plural': 'OrdersFix'},
        ),
        migrations.RenameIndex(
            model_name='orderfix',
            new_name='app_orders__session_07472f_idx',
            old_name='app_orders__session_087c5b_idx',
        ),
        migrations.RenameIndex(
            model_name='orderfix',
            new_name='app_orders__create__6b077f_idx',
            old_name='app_orders__create__28b3f0_idx',
        ),
        migrations.RenameIndex(
            model_name='orderfix',
            new_name='app_orders__update__7b7b3f_idx',
            old_name='app_orders__update__c082df_idx',
        ),
        migrations.RenameIndex(
            model_name='orderfix',
            new_name='app_orders__total_p_fa0d7c_idx',
            old_name='app_orders__total_p_e2c3ee_idx',
        ),
        migrations.RenameIndex(
            model_name='orderfix',
            new_name='app_orders__total_d_37dde8_idx',
            old_name='app_orders__total_d_c11468_idx',
        ),
        migrations.RenameIndex(
            model_name='orderfix',
            new_name='app_orders__total_c_24e1ab_idx',
            old_name='app_orders__total_c_976657_idx',
        ),
        migrations.RenameIndex(
            model_name='orderfix',
            new_name='app_orders__invoice_10cf94_idx',
            old_name='app_orders__invoice_00636c_idx',
        ),
        migrations.RenameIndex(
            model_name='orderfix',
            new_name='app_orders__is_deli_a056c5_idx',
            old_name='app_orders__is_deli_d368b7_idx',
        ),
    ]
