# Generated by Django 5.0.3 on 2024-05-07 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0012_rename_order_orderfix_alter_orderfix_options_and_more'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfix',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sessions.session'),
        ),
    ]
